### ISSUE TITLE
Reset Button

### ISSUE THREAD

**Issue by kaioto1** [gn0rrbitberrenbur/gn0rrbitberrenbur.github.io#1]
Dein Reset Button geht nicht, ich muss die Seite immer neu laden. Tbh nicht cool 👎🏻

**Comment by gn0rrbitberrenbur** [comment]
moinsen @kaioto1 , das ist tatsächlich kein bug sondern ein feature. ich will deinen ganzen ram mit den bildern vollladen. :)
